import type { SGFOProject } from "./types";

const now = new Date().toISOString();

/** Dados de demonstração (Metabase simulado + manual). Ids fixos para merge sem duplicar. */
export const MOCK_PROJECTS: SGFOProject[] = [
  {
    id: "mb-demo-1001",
    source: "metabase",
    metabaseId: "1001",
    contractId: "32100",
    eventName: "Feira de Negócios — Sul",
    clientName: "Cliente A",
    city: "Florianópolis",
    state: "SC",
    eventDate: "2026-05-10",
    status: "active",
    size: "G",
    responsible: "Ana R.",
    squad: "Sul",
    budgetStatus: "missing",
    budgetSource: "none",
    notes: "Mock: evento do Metabase — orçamento entra no SGFO via import Excel (Custos) ou aqui",
    importedAt: now,
    lastSyncedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mb-demo-1002",
    source: "metabase",
    metabaseId: "1002",
    contractId: "32101",
    eventName: "Roadshow Corporativo 2026",
    clientName: "Cliente B",
    city: "São Paulo",
    state: "SP",
    eventDate: "2026-08-20",
    status: "future",
    size: "M",
    responsible: "—",
    squad: "SP",
    budgetStatus: "missing",
    budgetSource: "none",
    notes: "",
    importedAt: now,
    lastSyncedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "man-demo-1",
    source: "manual",
    eventName: "Workshop interno (piloto)",
    clientName: "Casa",
    city: "Bragança Paulista",
    state: "SP",
    eventDate: "2026-04-30",
    status: "finished",
    size: "PP",
    responsible: "Thiago",
    squad: "Base",
    budgetStatus: "closed",
    budgetSource: "manual",
    plannedCost: 15000,
    approvedCost: 15000,
    realizedCost: 14800,
    notes: "Evento de teste manual",
    createdAt: now,
    updatedAt: now,
  },
];
